name: Automatic 24-Hour Redeployment

on:
  schedule:
    - cron: '1/5 * * * *'

jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      env:
        HOOK: ${{ secrets.DEPLOY_HOOK }}
      uses: wei/curl@1
      with:
        args: -X GET env.HOOK
